# Generated by Django 6.0.6 on 2026-06-22 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='net_quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity_on_hand',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('INGREDIENT', 'Ingredient'), ('CONSUMABIL', 'Consumabil')], default='INGREDIENT', max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unitary_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Costul unitar nu poate fi negativ')]),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='loss_factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0, message='Factorul nu poate fi negativ'), django.core.validators.MaxValueValidator(1.0, message='Factorul nu poate fi mai mare decat 1')]),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('unitary_cost__gte', 0.0), ('unitary_cost__isnull', True), _connector='OR'), name='unitary_cost_gte_0_or_null'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(condition=models.Q(('loss_factor__gte', 0.0), ('loss_factor__lte', 1.0)), name='loss_factor_between_0_and_1'),
        ),
    ]
