# Generated by Django 6.0.6 on 2026-07-01 05:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_rename_quantity_recipeingredient_net_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0, message='Cantitatea nu poate fi negativa')])),
                ('reason', models.CharField(choices=[('EXPIRAT', 'Expirat'), ('ARS', 'Ars'), ('STRICAT', 'Stricat'), ('SCAPAT', 'Scapat')], max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_losses', to='core.ingredient')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_losses', to='accounts.location')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0.0)), name='reportedloss_quantity_gte_0')],
            },
        ),
    ]
