# Generated by Django 6.0.6 on 2026-07-04 14:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('losses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffConsumptionBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Alege orice zi; sistemul va salva prima zi a lunii', verbose_name='Luna si Anul')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Valoarea nu poate fi negativa')])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption_budgets', to='accounts.location')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='amount_gte_0'), models.UniqueConstraint(fields=('location', 'month'), name='uq_location_month')],
            },
        ),
    ]
