# Generated by Django 6.0.6 on 2026-07-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losses', '0002_staffconsumptionbudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedloss',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportedloss',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
