# Generated by Django 6.0.6 on 2026-06-24 08:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_rename_quantity_recipeingredient_net_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cif', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cif',), name='uq_cif')],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('document_number', models.CharField(max_length=120)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='accounts.location')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='procurement.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0, 'Cantitatea de pe bon nu poate fi negativa')])),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0, 'Pretul unitar nu poate fi negativ')])),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.goodsreceipt')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='core.ingredient')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0), ('unit_price__gte', 0)), name='grl_quantity_unit_price_gte_0')],
            },
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(fields=('supplier', 'document_number'), name='uq_supplier_document_number'),
        ),
    ]
