# Generated by Django 6.0.6 on 2026-07-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
